version: '3.9'  

services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"  
    volumes:
      - .:/app  
    environment:
      - PYTHONDONTWRITEBYTECODE=1  
      - PYTHONUNBUFFERED=1  

volumes:
  db_data:  